project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "Citi-Bike NYC Data Viz"
  author:
    - Deha Ay (da3109)
    - Karma Istanbouli (ki2268)
  repo-url: https://github.com/YOUR_GITHUB_ACCOUNT/REPO_NAME
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


