# Conclusion


As Citi Bike establishes itself as an invaluable player in New York's transportation network, maintaining its quality, reliability, and accessibility is essential in guaranteeing its sustained growth. With the city making strides in supporting Citi Bike's growth through investments in planning and infrastructure, understanding its current operational patterns is crucial. Trends related to time and location can guide quality control, bike re-balancing efforts, and in assessing ridership demands. 

One clear result of our research is that a large majority of bike flow is in Manhattan. The concentration of bike inflow and outflow in Manhattan suggests that most Citi Bike trips end and begin in the borough. This is not necessarily surprising based on our broad understanding of ridership demographic at the company's inception however, as our interactive maps indicate, Citi Bike has expanded its station network across the boroughs over the years. Considering
the extensive station network expansion since launch, the disproportionate flow is fascinating and can be indicative of other factors related to station maintenance, pricing, affordability, etc. that may be worth addressing. 

Another interesting result is that hourly average net flow is consistently negative across different time aggregations. This could be interpreted in several ways. Intuitively, net flow is a way to estimate demand across stations, however it is not as straight-forward as it may seem. Positive net flow does not necessarily indicate higher demand or popular destinations. In reality, stations with positive net flow suggest that many people end their rides around that location, and can simply mean that there are usually  available docking spaces. On the other hand, Negative net flow suggests that many people start their rides at that location which could potentially indicate high demand in that area. It is clear that net flow is a nuanced metric and requires more analysis.

Other notable trends are that ridership is higher in the Summer and Fall months and on weekdays. The most popular origins and destinations are mostly in Manhattan but, in general, they are around transit areas such as Penn Station and Port Authority, and around popular recreational hubs like Central Park and neighboring areas like the Upper West Side.

As we moved forward with our analysis, it became clear that we were limited by our data. As our data was based on hourly averages across different time frames, we were unable to visualize more granular data such as actual trip numbers, where trips began and end, trip duration, rider demographics, all of which could have provided insightful results. While our analysis was interesting and insightful, this has only inspired more in-depth investigations of Citi Bike's role and impact in New York. 

